### ISSUE TITLE
Content Parse Exception at Similarity Search due to "model_id doesn't support values of type: VALUE_NULL"

### ISSUE THREAD

**Issue by DJ2695** [langchain-ai/langchain-elastic#57]
Hey there, 
I recently got back to a ElasticDB relying LLM project and got hit with following error when running a query (although i have not updated dependencies):

```cmd
BadRequestError: BadRequestError(400, 'x_content_parse_exception', 
"[1:142] [text_embedding] model_id doesn't support values of type: VALUE_NULL")
```

Executing script where it fails:
```python
from langchain_elasticsearch import ElasticsearchStore

# Instantiation
class ElasticVectorStore(ElasticsearchStore):

    def __init__(
        self, session_id: str, index: str, es_url: str, es_user: str, es_pw: str
    ):
        super().__init__(
            es_url=es_url, index_name=index, es_user=es_user, es_password=es_pw
        )
        self.session_id: str = session_id
        self.index = index
        self.embed: Callable[[str], list[float]] = EmbeddingModels.ADA_2.embed_query

    @classmethod
    def from_index(cls, session_id: str, index: str) -> "ElasticVectorStore":
        es_url = os.getenv("ELASTIC_API_BASE")
        es_user = os.getenv("ELASTIC_USER")
        es_pw = os.getenv("ELASTIC_PW")

        store = ElasticVectorStore(
            session_id=session_id,
            index=index,
            es_url=es_url,
            es_user=es_user,
            es_pw=es_pw,
        )

        try:
            store.client.indices.get(index=index)
            logger.info(f"Connected to index '{index}'.")
        except TransportError as error:
            logger.error(f"Index ({index}) not found: {error}")
            raise
        return store

# [... some class function]

# Later in the file at a function
if mode == "semantic":
            target_field_vector = target_field + "_vector"
            response = self.store.similarity_search(
                query=query, query_field=target_field_vector, k=size, filter=node_filter
            )
```
Dependency versions:
```toml
[tool.poetry.dependencies]
python = ">=3.11,<3.13"
tqdm = "^4.66.5"
langgraph = "^0.2.3"
elasticsearch = "^8.15.0"
arize-phoenix = "^4.23.0"
langchain-community = "^0.2.12"
langchain-openai = "^0.1.21"
langchain-elasticsearch = "^0.2.2"
colorist = "^1.7.3"
networkx = "^3.3"
python-dotenv = "^1.0.1"
tiktoken = "^0.7.0"
azure-identity = "^1.17.1"
azure-storage-blob = "^12.22.0"
```

Really looking forward for any sort of help. I saw that the `model_id` was newly introduced to also support hosted models in elastic. But i am not using hosted models in Elastic.
